apiVersion: v1
kind: Service
metadata:
  name: autocomplete-api
  labels:
    app: autocomplete
    role: api
    tier: backend
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8000
  selector:
    app: autocomplete
    role: api
    tier: backend
