apiVersion: v1
kind: Autocomplete
metadata:
    name: autocomplete-api
  # these labels can be applied automatically 
  # from the labels in the pod template if not set
  labels:
    app: autocomplete
    role: api
    tier: backend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically 
  # from the labels in the pod template if not set
  # selector:
  #   app: guestbook
  #   role: master
  #   tier: backend
  template:
    metadata:
      labels:
        app: autocomplete
        role: api
        tier: backend
    spec:
      containers:
      - name: autocomplete
      image: us.gcr.io/abowden-autocomplete/autocomplete  # or just image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8000
