# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0002_auto_20170524_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
